apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-java-kubernetes
spec:
  selector:
    matchLabels:
      app: train-ticket-java-kubernetes
  replicas: 3
  template:
    metadata:
      labels:
        app: train-ticket-java-kubernetes
    spec:
      containers:
        - name: spring-boot-k8s
          image: train-ticket-java:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191