  apiVersion: v1
  kind: Service
  metadata:
    name: train-ticket-java-kubernetes-svc
  spec:
    selector:
      app: train-ticket-java-kubernetes
    ports:
      - protocol: "TCP"
        port: 9191
        targetPort: 9191
    type: NodePort